server:
  port: 10001
spring:
  application:
    name: peak_cloud_palace
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
#        ephemeral: false # false表示开启永久实例在nocos上不会从服务列表中删除

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    port: ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:32606}/zse_test?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8&useAffectedRows=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: admin
    password: 123456
    # 使用druid数据源application.yml
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mq:
  evn: local
  socket:
    #单位为ms
    time: 120000 #2分钟
    broadcast:
      queue: ${mq.evn}.socket.broadcast.queue_
      exchange: ${mq.evn}.socket.broadcast.exchange
# ===== SocketIO配置 ===== #
socketio:
  # 每个room下socekt连接最大数量
  maxCountInRoom: 5
  # 检查token过期时间（单位：分钟）
  checkTokenExpiredTime: 2
  config:
    port: 10008
    bossCount: 1
    # 连接数大小
    workCount: 1000
    # 允许客户请求
    allowCustomRequests: true
    # 协议升级超时时间(毫秒)，默认10秒，HTTP握手升级为ws协议超时时间
    upgradeTimeout: 10000
    # Ping消息超时时间(毫秒)，默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 60000
    # Ping消息间隔(毫秒)，默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000
    # 设置HTTP交互最大内容长度
    maxHttpContentLength: 1048576
    # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576

# 内部调用密钥配置
inner:
  access:
    keyMap: {serverName: nkhLyBFs96bKeCpLj3bl6KKjH1GYymj1f/+yL/041rM=}