spring:
  application:
    name: purple-cloud-palace
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: xxxxxxxxxxxxxxxxx
#      discovery:
#        ip: ${nacos_discovery_ip}
#        port: ${nacos_discovery_port}
  main:
    allow-bean-definition-overriding: true

server:
  port: 10010
